### ISSUE TITLE
Toevoegen van een aantal attributen

### ISSUE THREAD

**Issue by RvdKlip** [maykinmedia/open-klant#158]
### Omschrijving / Description

Vanuit Rotterdam willen we een drietal gegevens toevoegen aan de bestaande attributen. Het betreft:
- Bankrekeningnummer 
- Voorkeurstaal 
- Voorkeurskanaal 
- 
### Added value / Toegevoegde waarde

Cluster Dienstverlening (DV) wil aanvullende gegevens van de Rotterdammer (burger, of bedrijf) enkelvoudig opslaan en meervoudig gebruiken. Aanvullende gegevens, die niet in de Basis Registratie Personen (BRP) staan en die we vastleggen voor een publieke taak, zoals taalvoorkeur, e-mailadres, telefoonnummer en bankrekeningnummer.  

Beweegredenen cluster DV: 
Het maakt de dienstverlening makkelijker, doordat de Rotterdammer niet iedere keer dezelfde gegevens hoeft in te vullen. 
Het maakt de dienstverlening betrouwbaarder, omdat er geen typefouten meer zijn en alle processen die dit gebruiken profiteren als we gegevens corrigeren. 
Het stelt de behoefte van de Rotterdammer centraal, omdat Rotterdammers aangeven: “vraag mij niet iedere keer naar de bekende weg. Jullie weten deze gegevens al?” 
Het geeft Rotterdammers regie over zijn/haar eigen gegevens 
We houden ons aan de AVG vereisten, zoals dataminimalisatie en inzage recht

we gebruiken het binnen mijngemeente (zie bijlage)
[Doc3.docx](https://github.com/maykinmedia/open-klant/files/14084280/Doc3.docx)
 

**Tasks**

* [ ] Add new resource Rekeningnummers
* [ ] Add relation from Partij to Rekeningnummers via `rekeningnummers` (one to many)
* [ ] Add relation from Partij to Rekeningnummers via `voorkeursRekeningnummer` (one to one)
* [ ] Add these fields to Rekeningnummer model:
  * `omschrijving` -- Een omschrijving van het rekeningnummer.
  * `bic` -- De unieke code van de bankinstelling waar de Partij het bankrekeningnummer heeft waarmee het subject in de regel internationaal financieel communiceert.	AN11	0..1
  * `iban` -- Het internationaal bankrekeningnummer, zoals dat door een bankinstelling als identificator aan een overeenkomst tussen de bank en een of meer subjecten wordt toegekend, op basis waarvan het Partij in de regel internationaal financieel communiceert.
* [ ] Partij needs to show the rekeningnummers and voorkeursRekeningnummer as inline
* [ ] You can set the voorkeursrekeningnummer via Partij

It should be all very similar to "kanaal" and "voorkeurskanaal".

**Comment by joeribekker** [comment]
Ok, kan je deze 2 attributen voor rekeningnummer toevoegen als gegevensgroep @bart-maykin 

https://www.gemmaonline.nl/index.php/Rsgb_3.0/doc/gegevensgroeptype/subject.rekeningnummer

Taal en kanaal hebben mee al
