### ISSUE TITLE
Als koploper wil ik aanvullingen op `Partij` die nog niet in het informatiemodel van VNG zitten

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-klant#69]
.. zodat ik mijn praktische use case kan invullen.

Opgevoerd bij VNG: https://github.com/VNG-Realisatie/klantinteracties/issues/272

**Tasks**

* [x] Add model `Categorie` with fields:
* [x] `naam` (charfield, max_length=80)
* [x] `beginDatum` (datefield, default=creation date if empty/not provided in API-call)
* [x] `eindDatum` (datefield, default=None)
* [x] Add FK from `Categorie` to `Partij` (`null=True`)
* [x] Add model to admin (as inline of Partij)
* [x] Add as read-only inline array to `Partij`
* [x] Make sure the resource description says: "Let op: Dit endpoint is **EXPERIMENTEEL**." en hetzelfde geldt bij de description van de read-only inline bij Partij: "Let op: Dit attribuut is **EXPERIMENTEEL**."

Update op taken:

In retrospect, you can link a category with start/end date per party, so we need to refactor a bit. 

* [x] Add new model, `CategorieRelatie` met API resource, marked with "EXPERIMENTEEL" like above.
* [x] Move the fields to this new model:
  * [x] `beginDatum` (datefield, default=creation date if empty/not provided in API-call)
  * [x] `eindDatum` (datefield, default=None)
* [x] Add FK from `CategorieRelatie` to `Categorie` (`null=True`)
* [x] Add FK from `CategorieRelatie` to `Partij` to `Partij` (`null=True`)
* [x] Remove the FK from `Category` to `Partij`

**Achtergrond**

Uit Excel (1):
![image](https://github.com/maykinmedia/open-klant/assets/96970/f7f1072e-32d9-4346-b05d-1dbe85abf137)

Uit Excel (2):
![image](https://github.com/maykinmedia/open-klant/assets/96970/dbb19b73-20e4-48f5-be82-b259aafb5814)

Dit stond verkeerd in de Excel (Eric) en moet niet aan Externe Identificatie maar aan Partij gekoppeld zijn.
![image](https://github.com/maykinmedia/open-klant/assets/96970/888fc146-4c76-4533-848a-0c5bb803f31c)

* [ ] 

**Discuss**

* [x] Categorie of CategorieRelatie? -> IM model benaming. Is gewoon categorie.
* [x] Wat is `CategorieType`? Is dat een enumeratie of vrije tekst? -> Door gemeente te onderhouden lijst
* [x] Moet `Categorie` niet `naam` heten? Het heeft al een relatie met "Categorie" -> check
* [x] Wat doen we met `Geldigheid` ivm historische gegevens die we niet opslaan? -> een categorie heeft een levensduur en staat eigenlijk los van overige historische gegevens.
* [x] Wat is `Looptijdtype`? -> staat hieronder uitgelegd.

**Comment by EvdMerwe** [comment]
De Excel is hier misschien niet duidelijk genoeg. Moeten we volgende week even doornemen. Ook is de naamgeving niet helemaal correct meer.

Hieronder de definitie van Looptijdtype zoals wij het in ons model gebruiken: 

![Looptijdtype definitie](https://github.com/maykinmedia/open-klant/assets/147585661/2f7cf890-8c64-48b2-bac7-25b9f7c0c0c6)
